name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install packages
        run: npm i
      - name: Build project
        run: npm run build-prod
      - name: Get build version
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: money-manager-ui-v${{ steps.package-version.outputs.version }}
          path: ./dist

  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
      - name: Display directory structure
        run: ls -R
